
substitutions:
  devicename: "ivt-vbx"
  
esphome:
  name: "$devicename"
  comment: "relay"
  platform: ESP8266
  board: esp01_1m

  on_boot:
    priority: -100
    then:
    - switch.turn_on: relay3

# Enable logging

logger:
  baud_rate: 0
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.249
    gateway: 192.168.2.1
    subnet: 255.255.255.0
# Enable Home Assistant API
api:
  encryption:
    key: "1234"

# Enable OTAs
ota:
  password: "1234"

time:
  - platform: homeassistant

uart:
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

sensor:
  - platform: uptime
    name: Relay Uptime

  - platform: wifi_signal
    name: Relay WiFi Signal
    update_interval: 60s
select:
  - platform: template
    name: Mode
    id: mode
    options:
     - "0V"
     - "115V"
     - "135V"
     - "150V"
     - "180V"
    initial_option: "135V"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            if (id(mode).state == "0V") {
              id(relay1).turn_off();
              delay(100);
              id(relay2).turn_off();
              delay(100);
              id(relay3).turn_off();
              delay(100);
              id(relay4).turn_off();
            }else if (id(mode).state == "115V") {
              id(relay1).turn_off();
              delay(100);
              id(relay2).turn_off();
              delay(100);
              id(relay3).turn_off();
              delay(100);
              id(relay4).turn_on();              
            }else if (id(mode).state == "135V") {
              id(relay1).turn_off();
              delay(100);
              id(relay2).turn_off();
              delay(100);
              id(relay3).turn_on();
              delay(100);
              id(relay4).turn_off();
            } else if (id(mode).state == "150V") {
              id(relay1).turn_off();
              delay(100);
              id(relay2).turn_on();
              delay(100);
              id(relay3).turn_off();
              delay(100);
              id(relay4).turn_off();
            } else if (id(mode).state == "180V") {
              id(relay1).turn_on();
              delay(100);
              id(relay2).turn_off();
              delay(100);
              id(relay3).turn_off();
              delay(100);
              id(relay4).turn_off();
            }
switch:
  - platform: restart
    name: "Restart"

  - platform: template
    name: 'Relay 1'
    id: relay1
    turn_on_action:
      - uart.write: [0xA0, 0x01, 0x01, 0xA2]
    turn_off_action:
      - uart.write: [0xA0, 0x01, 0x00, 0xA1]
    optimistic: true
    internal: true

  - platform: template
    name: 'Relay 2'
    id: relay2
    turn_on_action:
      - uart.write: [0xA0, 0x02, 0x01, 0xA3]
    turn_off_action:
      - uart.write: [0xA0, 0x02, 0x00, 0xA2]
    optimistic: true
    internal: true

  - platform: template
    name: 'Relay 3'
    id: relay3
    turn_on_action:
      - uart.write: [0xA0, 0x03, 0x01, 0xA4]
    turn_off_action:
      - uart.write: [0xA0, 0x03, 0x00, 0xA3]
    optimistic: true
    internal: true

  - platform: template
    name: 'Relay 4'
    id: relay4
    turn_on_action:
      - uart.write: [0xA0, 0x04, 0x01, 0xA5]
    turn_off_action:
      - uart.write: [0xA0, 0x04, 0x00, 0xA4]
    optimistic: true
    internal: true
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${devicename} - IP Address"
    ssid:
      name: "${devicename} - Wi-Fi SSID"
    bssid:
      name: "${devicename} - Wi-Fi BSSID"
  - platform: version
    name: "${devicename} - ESPHome Version"
    hide_timestamp: true        
